security:
  oauth2:
    client:
      clientId: 207829718149-hs7i5fbkak6fs7smmiu7eoq96cf269ua.apps.googleusercontent.com
      clientSecret: _VWYK7oKnieKLEUqOxi9SkcN
      accessTokenUri: https://oauth2.googleapis.com/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      scope: profile
      authenticationScheme: query
      clientAuthenticationScheme: none
    resource:
      userInfoUri: https://pspocmacys.appspot.com/